package com.github.david32768.jynxfor.my;

import static com.github.david32768.jynxfree.jynx.LogMsgType.*;

import com.github.david32768.jynxfree.jynx.JynxMessage;
import com.github.david32768.jynxfree.jynx.LogMsgType;

public enum Message implements JynxMessage {

    M22(WARNING,"value required (%d) for %s is more than limit value (%d); %d used"),
    M31(ERROR,"%s already set in line%n    %s"),
    M33(ERROR,"%s limit has already been set by line:%n  %s"),
    M34(ENDINFO,"some line numbers have been reduced mod %d as exceed unsigned short max"),
    M35(ERROR,"current value(%d) for %s excedes limit(%d)"),
    M36(ERROR,"label already defined in line:%n  %s"),
    M38(ERROR,"%s is not a valid char literal - blank assumed"),
    M40(ERROR,"duplicate %s: %s already defined at line %d"),
    M41(ERROR,"component can only appear in a record"),
    M42(ERROR,"%s invalid in context"),
    M43(ERROR,"line contains newline or carriage return character"),
    M45(ERROR,"value(%d) for %s exceeds that(%d) set by line:%n  %s"),
    M46(ERROR,"method %s has no body"),
    M47(ERROR,"Invalid component name - %s"),
    M48(ERROR,"number of Record components %d disagrees with number of instance fields %d"),
    M49(ERROR,"Invalid label - %s"),
    M50(ERROR,"Array type must be last - type %s found after array type %s"),
    M52(WARNING,"class name contains '$' but is not an internal class"),
    M53(WARNING,"as %s is not a static field, ' = %s' is silently ignored by JVM "),
    M54(ERROR,"variable %d has not been written to"),
    M55(ERROR,"duplicate %s: %s %s already defined at line %d"),
    M56(WARNING,"gap %d between local variables: %d - %d"),
    M58(ENDINFO,"used hint: %s is common supertype of %s and %s"),
    M59(ERROR,"method %s cannot be abstract in final class"),
    M60(WARNING,"local variables [%s ] are written but not read"),
    M65(ERROR,"local variables [%s ] are read but not written"),
    M71(WARNING,"as %s is not a final static field, ' = %s' may be silently ignored by JVM (JVMS 5.5 6)"),
    M75(ERROR,"Method %s failed %s check:%n    %s"),
    M78(ERROR,"%s has different signature %s to component %s"),
    M79(ERROR,"Trying to read beyond end of file"),
    M86(ERROR,"invalid op - %s"),
    M88(INFO,"options = %s"),
    M89(INFO,"file = %s version = %s"),
    M90(ERROR,"unused tokens - starting at %s"),
    M93(STYLE,"class name (%s) does not start with uppercase letter"),
    M95(ENDINFO,".line directives ignored as %s specified"),
    M96(ERROR,"syntax error in annotation field type"),
    M97(ERROR,"file(%s) does not have %s suffix"),
    M98(ERROR,"Unsupported version of %s: first parms are not compatible with:%n   %s"),
    M99(ERROR,"Separator '%s' not found in %s"),
    M100(ERROR,"Directive %s is not valid for %s"),
    M102(ERROR,"init method does not contain this or super: %s = %d %s = %d"),
    M103(WARNING,"init method contains %d %s and %d %s for net of %d"),
    M105(ERROR,"unknown option %s - ignored"),
    M106(ERROR,"labels in %s must not be defined yet"),
    M109(ERROR,"reserved word %s expected but found %s"),
    M111(ENDINFO,"instructions = %d labels = %d directives = %d pre_comments = %d"),
    M112(ENDINFO,"stackmap locals have been ignored as %s specified"),
    M113(ERROR,"value %s has 'L' suffix but must be a %s constant"),
    M115(ERROR,"Not first token - token = %s"),
    M116(BLANK,"%s created - size %d bytes"),
    M119(ERROR,"this and following lines skipped until %s"),
    M121(ERROR,"Instruction '%s' dropped as unreachable after '%s' without intervening label"),
    M122(ERROR,"invalid index (%d) for %s frame array [0,%d]"),
    M123(ERROR,"%s of %s failed because of %s"),
    M124(ERROR,"stack frame is definitely required here"),
    M126(INFO,"'%s %s' is required and has been added"),
    M127(ERROR,"directive %s reached before %s"),
    M128(ERROR,"% directive not allowed for component method %s"),
    M132(ERROR,"%s must have a %s method of type %s"),
    M133(ERROR,"package %s has already appeared in %s"),
    M134(ERROR,"boolean value is neither Boolean or Integer 0/1: value = %s class = %s"),
    M135(ENDINFO,"for consistency add %s prefix to method name for %s"),
    M138(ERROR,"%s cannot be used for constant - %s"),
    M139(ERROR,"%s prefix is invalid for %s"),
    M140(ERROR,"reading next token after reaching last"),
    M141(ERROR,"unknown constant; class = %s"),
    M143(INFO,"%s %s assumed"),
    M144(ERROR,"unknown value class = %s"),
    M145(ERROR,"Invalid method description %s"),
    M146(ERROR,"constant type = %s not valid in this context"),
    M152(ERROR,"zero length name"),
    M153(WARNING,"as class has a %s method it should have a %s method"),
    M154(ENDINFO,"%s changed to %s where necessary"),
    M155(ERROR,"code is not allowed as method is abstract or native"),
    M156(ERROR,"instance variables or methods with no %s method"),
    M157(ERROR,"%s%n  zero assumed"),
    M159(ERROR,"Invalid type - %s"),
    M163(ERROR,"stack underflow"),
    M164(ERROR,"stack overflow"),
    M166(ERROR,"top of stack(%s) is not a 32 bit type"),
    M168(ERROR,"unexpected directive(%s) in annotation"),
    M169(WARNING,"package %s used in %s has been added to %s"),
    M175(ERROR,"unknown Jynx desc = %c"),
    M176(ERROR,"%s not found as a macro library service"),
    M179(ERROR,"String length of %d exceeds maximum %d"),
    M180(ERROR,"top of stack(%s) and next on stack('%c') are not both 32 bit types"),
    M181(ERROR,"outer class must be absent if inner name is absent but is %s"),
    M182(ERROR,"top of stack is %s but required is %s"),
    M183(ERROR,"Type is not known - %s"),
    M184(ERROR,"current stack is %s but %s is %s"),
    M185(ERROR,"%s required for label %s is %s but currently is %s"),
    M187(ERROR,"annotation parameter count(%d) not in range[1,%d]"),
    M188(ERROR,"n (%d) is greater than current local size(%d)"),
    M189(LINE,"unneccessary case %d -> %s in %s as target is default label"),
    M190(ERROR,"mismatched local %d: required %s but found %s"),
    M191(ERROR,"method requires %s but found %s"),
    M193(LINE,"value required (%d) for %s is less than limit value (%d); %d used"),
    M194(ERROR,"annotation parameter count already been set"),
    M196(WARNING,"no %s instruction found"),
    M198(ERROR,"empty line - should not occur"),
    M199(ERROR,"field %s %s does not exist"),
    M201(ERROR,"frame element %s is not valid in %s context"),
    M203(WARNING,"potential infinite loop - catch using label equals catch from label"),
    M204(ERROR,"different types for %s; was %s but now %s"),
    M206(ERROR,"Invalid type letter '%c' (%d)"),
    M207(ERROR,"possible serialization method %s is not private"),
    M208(ERROR,"code not complete - last %s was %s"),
    M209(ERROR,"code not complete - last was %s"),
    M210(ENDINFO,"%s instruction ignored as not required"),
    M211(ERROR,"unknown symbolic variable: %s"),
    M212(ERROR,"%s not supported if %s specified"),
    M213(WARNING,"label %s defined before use - locals assumed as before last unconditional op"),
    M214(WARNING,"field %s %s does not exist in this class but may exist in superclass/superinterface"),
    M215(ERROR," %s field %s accessed by %s op %s"),
    M216(ERROR,"frame locals %s incompatible with current locals %s"),
    M217(ERROR,"from label %s is not before to label %s"),
    M218(INFO,"SYSIN will be used as input"),
    M220(WARNING,"label %s is an alias for label %s"),
    M221(ERROR,"required %s for var %d but found %s"),
    M222(ERROR,"either option %s is specified or file name is present but not both"),
    M223(ERROR,"Annotation for unknown variables [%s ]"),
    M224(WARNING,"invalid %s as only has %s: case 0 -> %s added"),
    M225(WARNING,"empty %s ignored"),
    M227(WARNING,"possible serialization method %s does not match %s"),
    M228(WARNING,"indent %d found but expected %d"),
    M229(ERROR,"ambiguous key %d; previous target = %s, current target = %s"),
    M230(ERROR,"attempting to overwrite %s using %s"),
    M231(WARNING,"Last instruction was %s: expected %s"),
    M232(ERROR,"Last instruction was %s: expected %s"),
    M233(ERROR,"Duplicate entry %s in %s: previous entry at line %d"),
    M234(ERROR,"invalid parameter number %d; bounds are [0 - %d)"),
    M238(ERROR,"error reading class file: %s"),
    M239(WARNING,"%s does not override object equals method in %s"),
    M240(ERROR,"%s is for internal use only"),
    M242(ERROR,"either init method %s is static or op  is not %s"),
    M243(ERROR,"%s op defined in %s has already been defined in %s"),
    M244(WARNING,"%s could be used as entries are consecutive"),
    M245(ERROR,"Unknown directive = %s"),
    M246(ERROR,"features for %s and %s differ"),
    M247(ERROR,"inner class %s must be different from %s %s"),
    M248(ERROR,"ELSE does not match an IF or TRY op"),
    M249(ERROR,"structured op(s) missing; level at end is %d"),
    M250(INFO,"the following own virtual method(s) are used but not found in class (but may be in super class or interface)%n    %s"),
    M251(WARNING,"own static method %s not found (but may be in super class)"),
    M252(ERROR,"own init method %s not found"),
    M253(ERROR,"illegal number of dimensions %d; must be in range [0,%d]"),
    M254(ERROR,"%s is used in a macro after a mulit-line op"),
    M255(WARNING,"duplicate key %d; target = %s"),
    M256(ERROR,"size of %s is %d which exceeds %d"),
    M257(ERROR,"argument count %d is not in range [0,%d]"),
    M259(ERROR,"dynamic constant is %s but %s expected"),
    M260(ERROR,"return type (%s) of invoke bootstrap method is not ( a known subtype of ) CallSite or Object"),
    M261(ERROR,"enclosing class name(%s) is not a prefix of class name(%s)"),
    M262(ERROR,"%s cannot be overridden"),
    M264(ERROR,"structured op mismatch: index %d in label stack is not in  range [0,%d]"),
    M265(ERROR,"structured op mismatch: label stack is empty"),
    M266(ERROR,"Label %s not defined; used in%n%s"),
    M267(ERROR,"%s has %d simple ops which exceeds maximum of %d"),
    M268(ERROR,"enclosing instance has already been defined%n   %s"),
    M269(ERROR,"component %s description %s differs from field description %s"),
    M270(WARNING,"%s directive missing but assumed"),
    M272(WARNING,"Label %s not used - defined in line:%n  %s"),
    M273(ERROR,"no Jynx directives in file!"),
    M274(SEVERE,"duplicate: %s has the same opcode(%d) as %s"),
    M275(ERROR,"descriptor '%s' for %s must start with '()'"),
    M276(ERROR,"empty element in  array"),
    M277(ERROR,"unexpected reserved word %s found"),
    M278(ERROR,"NaN type %#x is not in (0,%#x)"),
    M279(WARNING,"empty catch block - from label equals to label"),
    M280(BLANK,"program terminated because of severe error(s)"),
    M281(ERROR,"local variables [%s ] are in a frame but not written"),
    M282(ERROR,"instruction type '%c' (%s) of element at top of stack is not one of %s"),
    M284(ERROR,"label %s is not (yet?) known"),
    M285(SEVERE,"magic number is %#x; should be 0xcafebabe"),
    M287(WARNING,"JVM version %s is not supported by the version of ASM used; %s substituted"),
    M288(SEVERE,"JVM version %s is not supported by the version of ASM used; maximum version is %s "),
    M290(BLANK,";%s  %s -> %s"),
    M291(BLANK,";%s  %s = %s"),
    M292(BLANK,"%s  +%s"),
    M293(LINE,"print options = %s"),
    M294(LINE,"%s = %s"),
    M296(WARNING,"method %s%s not added as contains errors"),
    M297(ENDINFO,"package %s used in %s is not in %s (OK if package not in module)"),
    M299(ERROR,"Unexpected %s %s removed"),
    M300(ERROR,"required %s is missing"),
    M302(ERROR,"%s is null or has different feature requirement than %s"),
    M303(ERROR,"Enclosing method cannot be in enclosed class"),
    M304(ERROR,"%s has already been defined%n  %s"),
    M305(ENDINFO,"it is preferred that name is separated from owner by '%c' not '%c'"),
    M306(ERROR,"nested class have different owners; class = %s token = %s"),
    M307(ERROR,"final parameters [%s ] are overwritten"),
    M308(ERROR,"parameter number %d is not in range [0,%d]"),
    M309(ERROR,"missing %s %d : null parameter added"),
    M310(ERROR,"parameter %d has already been defined: %s"),
    M312(WARNING,"maximum code size of %d may have been exceeded; current size = [%d,%d]"),
    M313(ERROR,"final class cannot have %s"),
    M314(ENDINFO,"parameter type %s changed to %s"),
    M315(ENDINFO,"owner %s translated to %s"),
    M316(SEVERE,"only one label tester allowed"),
    M317(ERROR,"number of macro ops exceeds maximum of %d for %s"),
    M318(SEVERE,"op %s is not a valid op name"),
    M319(ERROR,"%s is an interface and so '%c' must be prepended to %s"),
    M320(ENDINFO,"occurences of %s have been ignored: %s"),
    M321(ERROR,"%d does not in [0,%d]"),
    M322(ERROR,"use of %s is not supported: %s"),
    M323(WARNING,"by adding dflt entries %s (size %d) would still be smaller than %s (size %d); range = %d labels = %d"),
    M324(ERROR,"translation %s -> %s is invalid; %s is not a valid key"),
    M325(ERROR,"translation %s -> %s is invalid; %s is not a valid value"),
    M326(BLANK,";%s  offset = [%d,%d]"),
    M328(WARNING,"%s nest level is already zero"),
    M329(INFO,"print options = %s"),
    M330(ERROR,"maximum code size of %d exceeded; method size = [%d,%d]"),
    M335(ERROR,"index (%d) is not a current try index [0,%d]"),
    M337(ERROR,"%s is predefined"),
    M338(ERROR,"code missing but method is not native or abstract"),
    M339(ERROR,"maximum code size of %d exceeded; current size = [%d,%d]"),
    M340(ERROR,"range of cases [%d, %d] is too big for %s, so %s substituted"),
    M341("invalid return type %s"),
    M362(ERROR,"expected arg %s but was %s"),
    M370(ERROR,"Type annotations not allowed for Module"),
    M394(ERROR,"END OF CLASS HEADER - SHOULD NOT APPEAR!; %s"),
    M400(ENDINFO,"unable to find %s %s because of %s"),
    M402(ERROR,"cannot insert end_token"),
    M403(WARNING,"duplicate %s hint for %s"),
    M404("different %s hint for %s: %s and %s"),
    M405(ERROR,"%s has different type %s from previous %s at line %d"),
    M406(ERROR,"method %s in %s class must be %s, not %s and have no parameters"),
    M407(ENDINFO,"%s %s is deprecated"),
    M408(ERROR,"expected %s but found %s"),
    M409(ERROR,"illegal operation on END_TOKEN"),
    M410(ERROR,"cannot amend quoted token"),
    M411(ERROR,"type %s not found"),
    M412(ERROR,"%s not supported"),
    M413("Verification: %s"),
    M617("circular hint: %s extends %s"),    
    M622("hints file does not have %s suffix"),
    M623("first directive in hints file is not %s"),
    M624(INFO,"ASM Simple Verifier used"),
    M626("key %d is not in range [%d,%d]"),
    M649(INFO,"ASM Simple Verifier used to try and clarify error reported by ClassFile.verify"),
    M800(ENDINFO,"line number 0 changed to 1; ASM Issue #317989"),
    M801(FINE,"min length = %d max length = %d"),
    M802(FINER,"at label %s: min length = %d max length = %d -> %d (adjusted = -%d)"),
    M901(ERROR,"unknown ASM type %s as it starts with '%c'"),
    M903(ERROR,"unknown class %s for ASM frametype"),
    M906(ERROR,"unknown ASM type - %s"),
    M907(ERROR,"unknown directive %s for context %s"),
    M908(ERROR,"unexpected Op %s in this instruction"),
    M990(BLANK,"%s"),
    M995(WARNING,"%s"),
    ;

    private final LogMsgType logtype;
    private final String format;
    private final String msg;

    private Message(LogMsgType logtype, String format) {
        this.logtype = logtype;
        this.format = logtype.prefix(name()) + format;
        this.msg = format;
    }
    
    
    private Message(String format) {
        this(ERROR,format);
    }

    @Override
    public String format(Object... objs) {
        return String.format(format,objs);
    }

    @Override
    public String getFormat() {
        return msg;
    }
    
    @Override
    public LogMsgType getLogtype() {
        return logtype;
    }
    
}
